### ISSUE TITLE
漂流瓶无法塞图片

### ISSUE THREAD

**Issue by XiaolanX** [windbullet/koishi-plugin-re-driftbottle#3]
![QQ截图20240624104542](https://github.com/windbullet/koishi-plugin-re-driftbottle/assets/67143380/42b4ec3c-95c6-4064-a7ea-792adf662c5e)

具体配置：`System:
    OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz

Binaries:
    Node: 20.14.0
    Yarn: 4.1.1

Koishi:
    Core: 4.17.9
    Console: 5.29.2`

**Comment by windbullet** [comment]
看起来像是适配器的问题

**Comment by XiaolanX** [comment]
那该咋办阿awa

**Comment by XiaolanX** [comment]
啊，换了个框架就好了awa
